<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    use HasFactory;

    protected $fillable = [
        'link_pendaftaran',
        'kontak',
        'status_pendaftaran',
        'nama_event',
        'deskripsi_event',
        'footer_text',
        'primary_color',
        'text_primary_color',
        'secondary_color',
        'text_secondary_color',
        'accent_color',
        'body_text_color',
        'font_family_url',
        'theme_slug',
        'about_image',
        'logo',
        'navbar_element',
        'top_image',
        'side_image_left',
        'side_image_right',
        'side_image_left_bottom',
        'side_image_right_bottom',
        'footer_image',
        'event_start',
        'event_end',
        'event_status',
        'is_save_the_date_active',
        'auto_update_status',
        'background_image',
        'background_color',
        'about_tag',
        'about_title',
        'lomba_tag',
        'lomba_title',
        'lomba_subtitle',
        'galeri_tag',
        'galeri_title',
        'galeri_subtitle',
        'galeri_limit',
        'faq_tag',
        'faq_title',
        'faq_subtitle',
        'about_experience_label',
        'about_experience_sublabel',
        'hero_primary_btn_text',
        'hero_secondary_btn_text',
        'footer_description',
        'reg_tag',
        'reg_title',
        'reg_subtitle',
        'reg_feature_1',
        'reg_feature_2',
        'reg_feature_3',
        'reg_form_title',
        'reg_form_subtitle',
        'hero_tag',
        'hero_title',
        'process_title1',
        'process_desc1',
        'process_icon1',
        'process_title2',
        'process_desc2',
        'process_icon2',
        'process_title3',
        'process_desc3',
        'process_icon3',
        'countdown_tag',
        'countdown_title',
        'countdown_subtitle',
        'about_feature1_title',
        'about_feature1_desc',
        'about_feature1_icon',
        'about_feature2_title',
        'about_feature2_desc',
        'about_feature2_icon',
        'about_feature3_title',
        'about_feature3_desc',
        'about_feature3_icon',
        'about_feature4_title',
        'about_feature4_desc',
        'about_feature4_icon',
        'about_btn_text',
        'footer_ig_link',
        'footer_map_link',
    ];
}
